
# ─── Original Author ──────────────────────────────────────────────────────────
custom:
  - " https://www.buymeacoffee.com/7wzcr2p9vxM/"    # louisnw01’s Buy Me a Coffee

github:
  - louisnw01       # Sponsor the original author

# ─── Maintainer ────────────────────────────────────────────────────────────────
github:
  - EsIstJosh       # Sponsor me on GitHub

custom:
  - "BTC: 3MTP3iMF6rxDARjfqr7QdmWrgWf3EQJK7w"
